[tools]
cookiecutter = "2.6.0"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks.create]
description = "Create a new KMP + Tuist project from template"
run = "./kmp-mobile-tuist create"

